# SPDX-FileCopyrightText: 2025 OCode
#
# SPDX-License-Identifier: Apache-2.0

version: '3.4'

services:
  gologseeker:
    image: go-logs-eeker
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5001:5001
  postgresql-db:
    image: postgres:16.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: go-logs-seeker-db
    ports:
      - 5432:5432
    volumes:
      - postgresql-data:/var/lib/postgresql/data

volumes:
  postgresql-data:
