# SPDX-FileCopyrightText: 2025 OCode
#
# SPDX-License-Identifier: Apache-2.0

version: '3.4'

services:
  gologseeker:
    image: gologseeker
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5001:5001
